CREATE DATABASE IF NOT EXISTS scholarmatch_auth CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE scholarmatch_auth;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  marks DECIMAL(5,2) NOT NULL DEFAULT 0,
  income BIGINT NOT NULL DEFAULT 0,
  category VARCHAR(50) NOT NULL DEFAULT 'any',
  gender VARCHAR(20) NOT NULL DEFAULT 'any',
  disability VARCHAR(10) NOT NULL DEFAULT 'no',
  state VARCHAR(100) NOT NULL DEFAULT 'any',
  education_level VARCHAR(50) NOT NULL DEFAULT 'any',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
